source 'http://rubygems.org'

gem 'unicorn'
gem 'puma'
gem 'falcon'
gem 'iodine'
gem 'activerecord-import'
gem 'activerecord'
gem 'rails'
gem 'tzinfo-data'
gem 'oj'

group :mysql do
  gem 'mysql2', '0.5.2'
end

group :postgresql do
  gem 'pg'
end
